### ISSUE TITLE
Duplicate style.css header

### ISSUE THREAD

**Issue by stebrech** [WPZOO/grunt#1]
`build:wpzoo` returns two headers in style.css. One for penguin, another for wpzoo.

**Comment by stebrech** [comment]
As well as it grabs an older version of the penguin stylesheet

**Comment by grappler** [comment]
I fixed the issue where it gets the older version of penguin stylesheet in https://github.com/grappler/WPZOO/commit/3fcc9512a6569118967b6c8e3214911b82ada944

Can you check again regarding the two headers?

**Comment by stebrech** [comment]
Works!
